apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Base64 encoded values. Example: echo -n "password" | base64
  # Default "password" -> cGFzc3dvcmQ=
  # Default "root" -> cm9vdA==
  db-pass: cGFzc3dvcmQ=
  db-user: cm9vdA==
